improvement(UN-658): conditionals added for edit and new CTAs
commutatus/cm-admin pull request #134
Opened 2022-03-04 09:22 UTC by jish0desarkar

1. Cursor pointer for drawer link
2. Conditional added for index more option dropdown
3. Conditioanl added for Add CTA
4. Tag string upcase

2022-03-04 14:15 UTC, AdityaTiwari2102 requested changes

2022-03-04 14:15 UTC, AdityaTiwari2102 commented on app/views/cm_admin/main/_table.html.slim
> +                        | Edit
@jish0desarkar - We can convert it to `link_to`.

2022-03-04 14:15 UTC, AdityaTiwari2102 commented on app/views/cm_admin/main/_top_navbar.html.slim
> +          | Add
@jish0desarkar - We can convert it to `link_to`

2022-03-11 13:28 UTC, anbublacky approved these changes

2022-03-11 14:22 UTC, AdityaTiwari2102 approved these changes

2022-03-11 14:22 UTC, AdityaTiwari2102 commented
@jish0desarkar - I have made the changes that were pending.

2022-03-11 14:23 UTC, merged