Sidebar icon
commutatus/cm-admin pull request #137
Opened 2022-03-13 05:54 UTC by anbublacky

2022-03-14 08:06 UTC, AdityaTiwari2102 commented on lib/cm_admin/view_helpers/page_info_helper.rb
> -          when 'show'
@anbublacky - Can you give some context why are we removing these?

2022-03-14 08:08 UTC, AdityaTiwari2102 commented
@anbublacky - I have updated the brach with develop since a few changes present are already merged. Also, can you change the title of this PR? I couldn't find anything related to sidebar icons here.

2022-03-17 15:37 UTC, anbublacky commented on lib/cm_admin/view_helpers/page_info_helper.rb
> -          when 'show'
@AdityaTiwari2102 Show page has breadcrumb and not the page description.  Since this is the fallback method even if we do not define anything through DSL it shows up on page, so removed this

2022-03-17 16:24 UTC, AdityaTiwari2102 requested changes

2022-03-17 16:24 UTC, AdityaTiwari2102 commented on app/assets/stylesheets/cm_admin/base/scaffold.scss
> +    background-color: #F3F4F6;
@anbublacky - We can use the SCSS variables instead

2022-03-17 16:24 UTC, AdityaTiwari2102 commented on app/assets/stylesheets/cm_admin/base/scaffold.scss
> +    color: #9CA7AE;
@anbublacky - We can use the SCSS variables instead

2022-03-17 16:24 UTC, AdityaTiwari2102 commented on lib/cm_admin/view_helpers/page_info_helper.rb
> -          when 'show'
Got it

2022-03-21 05:25 UTC, merged