Cmad 104 devise generator
commutatus/cm-admin pull request #208
Opened 2022-06-29 17:50 UTC by anbublacky

## JIRA Ticket
[CMAD-104](https://commutatus.atlassian.net/browse/CMAD-104)

## What?
- Generator to set up authentication in new projects

## Why?
- It takes a little bit of time to set up authentication and its a little manual process
- For a new project this would work and existing project similar steps are required.

2022-07-01 11:57 UTC, mikevic approved these changes

2022-07-04 04:36 UTC, AdityaTiwari2102 requested changes

2022-07-04 04:36 UTC, AdityaTiwari2102 commented on lib/generators/cm_admin/add_authentication_generator.rb
> +        inject_into_file 'app/models/user.rb', before: "end\n" do <<-'RUBY'
@anbublacky - Since we are asking the name for user model we should have the file path dynamically created, right?

2022-07-04 07:25 UTC, anbublacky commented on lib/generators/cm_admin/add_authentication_generator.rb
> +        inject_into_file 'app/models/user.rb', before: "end\n" do <<-'RUBY'
@AdityaTiwari2102 Yes bro. I was checking with the user as the default model and it worked.
I will try creating other models.

2022-07-05 05:13 UTC, AdityaTiwari2102 approved these changes

2022-07-05 09:49 UTC, merged