feat: introduce index config
commutatus/cm-admin pull request #21
Opened 2021-01-19 15:35 UTC by tambakoo

2021-01-20 13:45 UTC, mikevic requested changes
Overall feedback
1. What would the file structure be? Would the view files be automatically generated? 
2. Can we detail the gem installation as well? (add X to gem file, anything else?)
3. How would the controllers be structured?

2021-01-20 13:45 UTC, mikevic commented on index-config.md
> +block_html: #html code for tag type
@tambakoo - perhaps reference a view_helper rather than HTML?

2021-01-20 13:45 UTC, mikevic commented on index-config.md
> +value: #{table_data_value}
Can the view helper manage this?

2021-01-20 13:45 UTC, mikevic commented on index-config.md
> +min: #min value for range
Can you clarify how min/max would be used on the table header please?

2021-01-20 13:45 UTC, mikevic commented on index-config.md
> +1. Have a block for each data element.
I think this is a nice way forward, as long as there is a wrapper for the table.

2021-01-20 13:45 UTC, mikevic commented on index-config.md
> +error_message: #{error_message}
Wouldn't it be better to generate error messages based on the some attributes, for example required would generate a different message from max_length: 10

2021-01-20 13:45 UTC, mikevic commented on index-config.md
> +error_message_class: #{error_message_class}
I guess this would be standard for all forms based on the UI?

2021-01-21 17:09 UTC, raj-aditya commented on index-config.md
> +error_message: #{error_message}
@mikevic Yes bro we can do that. We can add an attribute 'required' for checking the presence of the value. But I think bro we can also add another attribute for custom error messages.

2021-01-21 17:14 UTC, raj-aditya commented on index-config.md
> +error_message_class: #{error_message_class}
@mikevic As we were adding custom error messages so we also need to have a class that can be used by the javascript function to show the error messages. Error_message_class will append the class to the block of validation message.

2021-01-22 11:47 UTC, tambakoo commented
> Overall feedback
> 
> 1. What would the file structure be? Would the view files be automatically generated?
> 2. Can we detail the gem installation as well? (add X to gem file, anything else?)
> 3. How would the controllers be structured?

1. These pseudo code blocks are only indicative. A real config file will have these blocks in some sort of a closure (mostly a do block). Generating the view files and associated javascript based on a configuration file is the objective here.
2. This will follow as we develop this library further.

2021-01-22 11:52 UTC, tambakoo commented
> Overall feedback
> 
> 1. What would the file structure be? Would the view files be automatically generated?
> 2. Can we detail the gem installation as well? (add X to gem file, anything else?)
> 3. How would the controllers be structured?

1. These pseudo code blocks are only indicative. A real config file will have these blocks in some sort of a closure (mostly a do block). Generating the view files and associated javascript based on a configuration file is the objective here.
2. This will follow as we develop this library further.
3. This is something we're still discussing how to proceed with. Mostly controllers will have _some_ degree of business logic which is very app specific, so we're not sure if we should write controllers. But another thought is - like scaffold generators we should write controllers with dummy basic methods (whose views we create). Looking for ideas here.

2021-01-25 01:46 UTC, mikevic commented on index-config.md
> +error_message_class: #{error_message_class}
@raj-aditya - I'm still not convinced about the custom_message, here are the reasons why
1. If the errors are on the frontend, the use cases will not just be a for a particular field but rather common across the framework such as required, max-length etc.
2. With the current definition, without the logic in place, how will the field know when it is a custom error and not a general error such as required.
3. I don't see how we can implement multiple errors with just the custom message.
4. If the errors are backend, they will be returned by the backend.
5. The design system implements only a couple of ways to show errors, why not just tap into those?

2021-01-25 01:56 UTC, mikevic commented
> > Overall feedback
> > 
> > 1. What would the file structure be? Would the view files be automatically generated?
> > 2. Can we detail the gem installation as well? (add X to gem file, anything else?)
> > 3. How would the controllers be structured?
> 
> 1. These pseudo code blocks are only indicative. A real config file will have these blocks in some sort of a closure (mostly a do block). Generating the view files and associated javascript based on a configuration file is the objective here.
> 2. This will follow as we develop this library further.
> 3. This is something we're still discussing how to proceed with. Mostly controllers will have _some_ degree of business logic which is very app specific, so we're not sure if we should write controllers. But another thought is - like scaffold generators we should write controllers with dummy basic methods (whose views we create). Looking for ideas here.

@tambakoo 
1. OK, however, as @anbublacky mentioned in another config, I'd like to see an entire index file in place.
2. OK, can we have this in the next iteration?
3. I've written my ideas on the discussion -  #22

2021-01-27 03:54 UTC, sajinmp reviewed
There are default views and functions right? I believe there should be something that the user of the gem can configure quickly without having to write much code at all. These should be customizations and stuff. 

I was not able to figure out what would be generated if the data is provided in either of the ways mentioned. Will these blocks for the data elements/forms/filters etc affect only the data elements? Will the user have to write the layout and stuff for the page.

Regarding the error messages, I think that is better handled from the back-end. Ability to handle the error must be provided to the user. 

I am not really sure how its implementation will look like. It would be great if more info would be provided on how it will work - like what is the minimum configuration required to get a fully functional admin page, how it can be customized etc - as that'll help understand a lot of scenarios.

2021-01-28 12:26 UTC, raj-aditya commented on index-config.md
> +error_message_class: #{error_message_class}
@mikevic To solve the these problem what we have thought:

1. To add attributes such as required, max-length etc and generate error message based on the input by the user.
2. Also keep the error_message block for custom messages
3. The backend error will be shown on the top of the form.

2021-01-28 16:16 UTC, mikevic commented on index-config.md
> +error_message_class: #{error_message_class}
@raj-aditya - bro, can you give me an example for custom messages. I am still not clear on the use case and a real-world example will help

2021-01-31 09:15 UTC, raj-aditya commented on index-config.md
> +error_message_class: #{error_message_class}
@mikevic For eg: if we want to have a validation for email which check that the email entered is of Commutatus only. For that we can add a custom validation 'only commutatus email accepted'.

2021-01-31 12:47 UTC, mikevic commented on index-config.md
> +error_message_class: #{error_message_class}
@raj-aditya - thanks, can you tell me how the implementation of this would work? For example, I'll add in the message that only "commutatus emails are accepted", how would this be triggered?

2021-02-01 13:27 UTC, raj-aditya commented on index-config.md
> +error_message_class: #{error_message_class}
@mikevic bro, a html tag will be generated with the error_message inside it which will be added below the input field. A javascript function can be used to trigger and show the error message.

2021-02-01 15:28 UTC, mikevic commented on index-config.md
> +error_message_class: #{error_message_class}
@raj-aditya - so again, if a custom JS function is used for this, why can't the JS function just provide the error. I feel it would be better to have the JS function emit the error because there maybe a case where there are two custom errors that we want to check for.

2021-02-02 12:31 UTC, raj-aditya commented on index-config.md
> +error_message_class: #{error_message_class}
@mikevic Yes bro we can do that.

2021-06-10 03:33 UTC, closed without merging