feat: Add custom html attr for all form fields
commutatus/cm-admin pull request #483
Opened 2024-06-20 07:17 UTC by ayzahamid-cm

## What does this change do?

We can pass custom classes and other attributes like `readonly`, `disabled`, `maxlength` etc directly as `html_attr` in form field.

## Why is this change needed?

Passing custom classes and attributes directly in form fields

## How were the changes done?

## How was testing done?

## Screenshots/Recording (optional)

https://github.com/commutatus/cm-admin/assets/169035791/c244a941-f51f-470f-b64e-be8d56f04e38

## Anything Else?

2024-06-20 20:49 UTC, mikevic commented
@ayzahamid-cm - could you take care of the rubocop warnings associated with style please? This will make the PR a bit more readable! 😅

2024-06-20 20:51 UTC, mikevic requested changes

2024-06-21 04:19 UTC, anbublacky approved these changes

2024-06-21 11:47 UTC, mikevic commented on lib/cm_admin/view_helpers/form_field_helper.rb
> +                          }, cm_field.html_attr )
@anbublacky - but it accepts multiple HTML attributes inside it.

2024-06-21 11:51 UTC, anbublacky commented on lib/cm_admin/view_helpers/form_field_helper.rb
> +                          }, cm_field.html_attr )
Yes, But still for me its single hash. We can go with `html_attrs`

2024-06-21 11:52 UTC, mikevic commented on lib/cm_admin/view_helpers/form_field_helper.rb
> +                          }, cm_field.html_attr )
@ayzahamid-cm - can you make this change? We can merge this PR then!

2024-06-21 11:53 UTC, ayzahamid-cm commented on lib/cm_admin/view_helpers/form_field_helper.rb
> +                          }, cm_field.html_attr )
@mikevic Sure 👍🏻

2024-06-21 12:38 UTC, ayzahamid-cm commented on lib/cm_admin/view_helpers/form_field_helper.rb
> +                          }, cm_field.html_attr )
@mikevic We also have to update from the project where we are passing `html_attr` in fields.

2024-06-21 12:39 UTC, mikevic commented on lib/cm_admin/view_helpers/form_field_helper.rb
> +                          }, cm_field.html_attr )
@ayzahamid-cm - sure; but which projects are using it? Any idea? I assumed this was a new field and note deployed!

2024-06-21 12:40 UTC, ayzahamid-cm commented on lib/cm_admin/view_helpers/form_field_helper.rb
> +                          }, cm_field.html_attr )
@mikevic I think only nadim is using this for now.

2024-06-21 12:46 UTC, mikevic commented on lib/cm_admin/view_helpers/form_field_helper.rb
> +                          }, cm_field.html_attr )
@ayzahamid-cm - thats okay; since CM Admin on NADIM is not on prod

2024-06-21 18:03 UTC, ayzahamid-cm commented on lib/cm_admin/view_helpers/form_field_helper.rb
> +                          }, cm_field.html_attr )
@mikevic Renamed to `html_attrs`
[here](https://github.com/commutatus/cm-admin/pull/483/commits/ce82dabdfbc6b7b41273c4752ebff86e02539b71)

2024-06-21 21:22 UTC, merged