infra: load action modal from ajax request
commutatus/cm-admin pull request #505
Opened 2024-07-19 15:49 UTC by Mahaveer1141

## What does this change do?
- load action modal from Ajax request

## Why is this change needed?
- too many modals load at once on the index.

## How were the changes done?
- added a new action to load modal.
- updated action dropdown in index for action details
- sending a ajax request on click of action button.

https://github.com/user-attachments/assets/c79bee59-030a-4a7d-963e-798b5ffefb4c

2024-07-24 10:50 UTC, mikevic approved these changes

2024-07-24 10:51 UTC, Mahaveer1141 commented on app/assets/javascripts/cm_admin/custom_action.js
> +      url: `/cm_admin/${modelName}/${recordId}/custom_action_modal/${actionName}`,
@mikevic I fixed this

2024-08-01 04:17 UTC, anbublacky requested changes

2024-08-01 04:17 UTC, anbublacky commented on app/controllers/cm_admin/resource_controller.rb
> +        custom_action = @model.available_actions.select { |x| x.name == params[:action_name].to_s }.first
@Mahaveer1141 This variable is not used, Can we remove it

2024-08-01 04:24 UTC, Mahaveer1141 commented on app/controllers/cm_admin/resource_controller.rb
> +        custom_action = @model.available_actions.select { |x| x.name == params[:action_name].to_s }.first
@anbublacky this variable is being used in partial

2024-08-01 04:50 UTC, anbublacky commented on app/controllers/cm_admin/resource_controller.rb
> +        custom_action = @model.available_actions.select { |x| x.name == params[:action_name].to_s }.first
@Mahaveer1141 This is not a instance variable and not passed through locals, SO it is not used right?

2024-08-01 04:57 UTC, Mahaveer1141 commented on app/controllers/cm_admin/resource_controller.rb
> +        custom_action = @model.available_actions.select { |x| x.name == params[:action_name].to_s }.first
@anbublacky this is being used, in this next line I am passing this to locals variable

2024-08-01 04:58 UTC, anbublacky approved these changes

2024-08-01 04:58 UTC, merged