feat: Column DSL (CMAD-24)
commutatus/cm-admin pull request #51
Opened 2021-05-31 08:36 UTC by charith08

2021-05-31 10:04 UTC, anondita commented on lib/cm_admin/models/column.rb
> +      attr_accessor :db_column_name, :column_type, :header, :format, :prefix
we can add suffix here too, also I think it will be great if we can validate the inputs of these format and return an error message

2021-05-31 10:15 UTC, charith08 commented on lib/cm_admin/models/column.rb
> +      attr_accessor :db_column_name, :column_type, :header, :format, :prefix
Suffix     - Yes bro, I have put it in the ToDo (2nd point) already 👍🏼 
Validate - Correct, I just kept this PR simple so that validations on the whole can be handled separately, in another PR (I've mentioned the same in [PR descritption](https://github.com/commutatus/cm-admin/pull/51#issue-658121794))

2021-05-31 10:17 UTC, anondita commented on lib/cm_admin/models/column.rb
> +      attr_accessor :db_column_name, :column_type, :header, :format, :prefix
Oh, awesome bro!

2021-05-31 11:21 UTC, mikevic requested changes

2021-05-31 11:21 UTC, mikevic commented on app/views/cm_admin/main/_table.html.slim
> +          th = column.header.present? ? column.header.to_s.titleize : column.db_column_name.to_s.titleize
@charith08 - how about making this into a view helper? I guess that would be the best place for this kind of logic that can be easily "complicated" even more later.

2021-05-31 11:32 UTC, charith08 commented on app/views/cm_admin/main/_table.html.slim
> +          th = column.header.present? ? column.header.to_s.titleize : column.db_column_name.to_s.titleize
@mikevic - Yes bro 👍🏼 I've already mentioned it on Todo (point 1), will do it.

2021-05-31 11:32 UTC, mikevic approved these changes

2021-06-01 04:57 UTC, AdityaTiwari2102 reviewed
@charith08 - Can we have the PR in the draft instead? I feel there are a lot of things that are yet to be implemented to make it work the way we have thought or pictured it.

2021-06-01 04:57 UTC, AdityaTiwari2102 commented on app/views/cm_admin/main/_table.html.slim
> +          th = column.header.present? ? column.header.to_s.titleize : column.db_column_name.to_s.titleize
@charith08 @mikevic - We can also store it directly in the available_fields under header while we are initializing the columns. Since we need to use it at multiple places, tables and exports, we can save some time in computing the logic. If it gets complicated it will reduce a lot of computation time. We can abstract the code in the controller as well.

2021-06-01 07:41 UTC, charith08 commented on app/views/cm_admin/main/_table.html.slim
> +          th = column.header.present? ? column.header.to_s.titleize : column.db_column_name.to_s.titleize
^ Added to [ToDo](https://github.com/commutatus/cm-admin/pull/51#issue-658121794)

2021-06-01 07:41 UTC, charith08 commented
> @charith08 - Can we have the PR in the draft instead? I feel there are a lot of things that are yet to be implemented to make it work the way we have thought or pictured it. If anyone wants to use the code they can checkout to the branch.

@AdityaTiwari2102 - Can be done 👍🏼 
It's for sure not the complete feature, but a base layout to get things started if someone else is dependent on column dsl. Anbu has also suggested we get the basic working code out to clear any dependencies and have small PRs.
@anbublacky - Let me know your thoughts on this PR bro, if [ToDo](https://github.com/commutatus/cm-admin/pull/51#issue-658121794) is to be handled in this same or another PR.

2021-06-09 13:19 UTC, merged