Added Documentation for Hiding Content and Listing of Select Two
commutatus/cm-admin pull request #526
Opened 2024-08-13 07:15 UTC by austinjb32

## What does this change do?

- Added Documentation for Hiding Contents, Listing Items in Select Two

## Why is this change needed?

## How were the changes done?

## How was testing done?

## Screenshots/Recording (optional)

## Anything Else?

2024-08-13 07:18 UTC, austinjb32 commented
These are the Contents
# Hide or Show Section and Fields 🦹

This module provides methods for hiding form sections and fields with HTML attributes.

## Method 1: Using HTML Attributes and JavaScript for Form Section

### Ruby: Form Section Definition

This Ruby code snippet defines a form section for "Private Van" with several fields.

```ruby
cm_section 'Private Van', html_attrs: { "data-behaviour" => "private_van-section"} do
  form_field :transport_vehicle_number, input_type: :string, label: 'Vehicle Number'
  form_field :transport_vehicle_in_charge, input_type: :string, label: 'Vehicle In Charge'
  form_field :transport_vehicle_in_charge_phone, input_type: :integer, label: 'Vehicle In Charge Phone'
end
```

This JavaScript code manages the visibility of the "Private Van" section based on a condition.

```javascript
$(document).on("turbo:load", function() {
  $(document).on('change', 'select[data-behaviour="transport_type-select"]', handleTransportTypeChange);
});

function handleTransportTypeChange(event) {
  // Get the section element by its data attribute
  var section = $('div[data-behaviour="private_van-section"]');
  
  // Get the selected value
  var selectedValue = $(event.target).val();
  
  // Toggle the visibility based on the condition
  if (selectedValue !== "private_van") {
    section.addClass('hidden');
  } else {
    section.removeClass('hidden');
  }
}
```

## Method 2: Using `display_if` Attribute for Form Section
This Ruby code snippet defines a form section for "Private Van" with several fields.

### Ruby: Form Section Definition

```ruby
cm_section 'Private Van', display_if:->(trip){trip.transport_type== "private_van" } do
  form_field :transport_vehicle_number, input_type: :string, label: 'Vehicle Number'
  form_field :transport_vehicle_in_charge, input_type: :string, label: 'Vehicle In Charge'
  form_field :transport_vehicle_in_charge_phone, input_type: :integer, label: 'Vehicle In Charge Phone'
end
```

### Ruby: Form Field Definition

```ruby
form_field :transport_vehicle_number, input_type: :single_select,collection: :mode_of_transport, display_if:->(trip){
  trip.transport_type=="private_van" }
```



💡Note: The `display_if` attribute is used to conditionally display the section based on the value of `trip.transport_type`. It doesn't updated in real time like the JavaScript method.

2024-08-14 02:15 UTC, mikevic requested changes

2024-08-14 02:15 UTC, mikevic commented on docs/ListingSelectTwoAjax.md
> +# Lisiting of Select Two using Ajax 🅰️
```suggestion
# Population of drop-downs using Ajax 🅰️
```

2024-08-14 02:15 UTC, mikevic commented on docs/ListingSelectTwoAjax.md
> +## Method 1: Using Ajax URL for Form Field
@austinjb32 - bro, from what I understand here, we need both methods to implement it successfully right? I suggest we then call them `Steps`, rather than `Methods`

2024-08-14 02:15 UTC, mikevic commented on docs/ListingSelectTwoItems.md
> +The `cm_section` method is used to define a form section with fields and custom HTML attributes. The example below demonstrates how to create a section with a single-select field using collection arr
Why are we talking about cm_section here? We should be specific and only talk about the form field. If the developer wants to, they can decide whether to include the form_field into a section or not.

2024-08-14 02:15 UTC, mikevic commented on docs/ListingSelectTwoItems.md
> +## Method 3: Using Helper Method for Form Field
@austinjb32 - I feel method 1 & 3 are pretty much the same bro, we can merge them.

2024-08-14 02:15 UTC, mikevic commented on docs/ListingSelectTwoItems.md
> +transport_type = Constant.where(type:"transport_type").all.map { |item| [item.full_name, item.id] }
```suggestion
transport_type = Constant.where(type: :transport_type).all.map { |item| [item.full_name, item.id] }
```

Space after `:`, always!

2024-08-14 02:15 UTC, mikevic commented on docs/ShowHideContent.md
> +cm_section 'Private Van', html_attrs: { "data-behaviour" => "private_van-section"} do
=>, use updated Ruby syntax.

2024-08-14 02:15 UTC, mikevic commented on docs/ShowHideContent.md
> +```javascript
@austinjb32 - mention where this code should be placed.

2024-08-14 04:08 UTC, austinjb32 commented on docs/ListingSelectTwoAjax.md
> +## Method 1: Using Ajax URL for Form Field
@mikevic The one with ajax_url is inbuilt cm-admin feature and the second is a custom method that i have done to pass additional parameters other than search.

2024-08-14 11:02 UTC, mikevic commented on docs/ListingSelectTwoAjax.md
> +                        more: data.length === 10
@austinjb32 - Bro, I don't see any pagination here, we'll need to set the page size to 10, right? Not sure how this works?

2024-08-19 04:25 UTC, austinjb32 commented on docs/ListingSelectTwoAjax.md
> +                        more: data.length === 10
i have fixed the code with the one in the geist

2024-08-21 11:34 UTC, mikevic approved these changes

2024-08-21 11:35 UTC, merged