Feat:PRO-5823:Added Alert Banner Functionality
commutatus/cm-admin pull request #535
Opened 2024-08-29 17:44 UTC by austinjb32

## What does this change do?

- Added Alert Functionality

## Why is this change needed?

## How were the changes done?

## How was testing done?

## Screenshots/Recording (optional)

## Anything Else?

2024-08-30 03:42 UTC, mikevic requested changes

2024-08-30 03:42 UTC, mikevic commented on app/views/cm_admin/main/_show_content.html.slim
> +  -unless @alerts.empty?
```suggestion
  - unless @alerts.empty?
```

2024-08-30 03:44 UTC, mikevic requested changes

2024-08-30 03:44 UTC, mikevic commented on lib/cm_admin/view_helpers/field_display_helper.rb
> +        alert_icon_info = { warning: 'triangle-exclamation', danger: 'triangle-exclamation', success: 'circle-check' }
```suggestion
        alert_icon_info = { warning: 'triangle-exclamation', danger: 'triangle-exclamation', success: 'circle-check' }
```

Is there a reason why this is called `alert_icon_info`? From what I see, it is the defaults based on the type of alert set

2024-08-30 05:01 UTC, anbublacky requested changes

2024-08-30 05:01 UTC, anbublacky commented on lib/cm_admin/view_helpers/field_display_helper.rb
> +        alert.body = alert.body.is_a?(Array) ? alert.body : [alert.body]
We can mandate body to be array right? Even if it is single or multiple

2024-08-30 05:01 UTC, anbublacky commented on lib/cm_admin/view_helpers/field_display_helper.rb
> +        alert_icon_info = { warning: 'triangle-exclamation', danger: 'triangle-exclamation', success: 'circle-check' }
@mikevic I believe the keys are based on the alert type and used.

2024-08-30 05:41 UTC, austinjb32 commented on lib/cm_admin/view_helpers/field_display_helper.rb
> +        alert.body = alert.body.is_a?(Array) ? alert.body : [alert.body]
@anbublacky Please check I have added an argument error if not array

2024-08-30 05:43 UTC, mikevic commented
@austinjb32  - Bro, can you also add in the docs with this feature? Thanks!

2024-08-30 10:30 UTC, barath46 commented on app/views/cm_admin/main/_alert_banner.html.slim
> +    .d-flex.justify-content-between.align-items-start.py-1
@austinjb32 Same here

2024-08-30 10:31 UTC, barath46 commented on app/views/cm_admin/main/_alert_banner.html.slim
> +    .d-flex.justify-content-between.align-items-center
@austinjb32 Same here

2024-08-30 10:32 UTC, barath46 requested changes
Requested changes

2024-09-02 22:05 UTC, mikevic approved these changes

2024-09-09 11:55 UTC, mikevic approved these changes

2024-09-09 12:01 UTC, merged