Role management
commutatus/cm-admin pull request #539
Opened 2024-09-03 12:27 UTC by anbublacky

## What does this change do?
- Add permission feature to the application

## Why is this change needed?
- Pundit policy can be made optional now. We can define policies from the application and set a scope for it.

## How were the changes done?
- Created Model for Role and Permission. Created CmAdmin Changes for the same.
- Created route to save the permission.
- Policies generated dynamically via the cm-admin, like how controller is generated.
- We can set scope for each action via the DSL for each model.

## How was testing done?
- Checked with geist project.
- Enabling an action and checking if the button gets disabled.
- Added a scope and checked if the scope is applied.

## Screenshots/Recording (optional)
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/5e8db2f9-01f2-43ac-abd8-4a089ff73d92">

## Anything Else?

2024-09-09 12:11 UTC, mikevic requested changes
@anbublacky 
1. Can we add docs on how to use this feature? It can be a separate page. 
2. What is the name of the task to add the migration for roles? 
3. Can we name the tables as cm_roles and cm_permissions? The main reason is to avoid clashing with any tables that are already present on the application. 
4. On the Geist PR, I saw some CSS that is added for this feature, can we add the CSS on CM Admin itself rather than on the project? 
5. Can you point me to where the default permission for admin is defined?

2024-09-09 12:11 UTC, mikevic commented on app/views/cm_admin/roles/permissions.html.slim
> +                = model.name.titleize
```suggestion
                = model.name.titleize
```

@anbublacky - we should default to the display_name of the model

2024-09-09 12:11 UTC, mikevic commented on lib/cm_admin/model.rb
> +      # klass = Class.new(policy) do
@anbublacky - we should delete this?

2024-09-10 13:18 UTC, anbublacky commented
1. Can we add docs on how to use this feature? It can be a separate page.
   - .md file added
2. What is the name of the task to add the migration for roles?
   - rake cm_admin:install_role
3. Can we name the tables as cm_roles and cm_permissions? The main reason is to avoid clashing with any tables that are already present on the application.
   - Done
4. On the Geist PR, I saw some CSS that is added for this feature, can we add the CSS on CM Admin itself rather than on the project?
   - Migrated the CSS.
5. Can you point me to where the default permission for admin is defined?
  - rake task will create default migration. Linking the user to role to be manually done.

2024-09-10 18:28 UTC, barath46 approved these changes

2024-09-13 05:11 UTC, merged