CMAD - 20 | Show page
commutatus/cm-admin pull request #68
Opened 2021-06-17 13:11 UTC by anondita

Example DSL used (proposed):
`cm_show do
      page_title :full_name
      page_description :description
      nav_item :overview, '#', true
      nav_item :table, '#', false
      nav_item :history, '#', false
      cm_show_section "Description" do
	      field :first_name, label: 'First Name'
	      field :last_name, label: 'Last name'
	      field :email, label: 'Email'
	    end
	    cm_show_section "Additional data" do
	      field :dob, label: 'Date of birth'
	      field :status, label: 'status'
	    end
	    cm_show_section "Description" do
	      field :first_name, label: 'First Name'
	      field :last_name, label: 'Last name'
	      field :email, label: 'Email'
	    end
	    cm_show_section "Additional data" do
	      field :dob, label: 'Date of birth'
	      field :status, label: 'status'
	    end
    end`
    
    Output:
    
![image](https://user-images.githubusercontent.com/43874191/122402944-9153c980-cf9b-11eb-9e45-53daeed1a7ac.png)

2021-06-17 13:19 UTC, anondita commented
![image](https://user-images.githubusercontent.com/43874191/122404167-9cf3c000-cf9c-11eb-9163-bff85591b9c2.png)
Example DSL used:

2021-08-31 10:28 UTC, anbublacky requested changes

2021-08-31 10:28 UTC, anbublacky commented on app/views/cm_admin/main/index.html.slim
> +.index-page.page-container
Name the top class with cm-index-page, So it does not get overwritten in application

2021-08-31 10:28 UTC, anbublacky commented on app/views/layouts/cm_admin.html.slim
> +                == render 'cm_admin/main/tabs'
Can you check if this can be reused? it looks the same

2021-08-31 10:28 UTC, anbublacky commented on lib/cm_admin/model.rb
> +      @page_description = page_description
I remember writing a helper, if the page_title or description is empty. Can you check  we can remove this.

2021-08-31 10:28 UTC, anbublacky commented on lib/cm_admin/model.rb
> +>>>>>>> 0ed78242394a8de0a9cafdcff5bf658fd94c17af
Remove this, See if everything is merged properly

2021-08-31 10:28 UTC, anbublacky commented on lib/cm_admin/model.rb
> +        end
Shouldn't this be inside action when initialized, check based on layout type?

2021-08-31 10:28 UTC, anbublacky commented on lib/cm_admin/models/cm_show_section.rb
> +        puts "For printing field #{field_name}"
Remove all the puts statement

2021-08-31 10:28 UTC, anbublacky commented on lib/cm_admin/models/filter.rb
> +          records = self.name.constantize.where(nil) unless records
Does filter class have a name?

2021-08-31 10:29 UTC, anondita commented on lib/cm_admin/model.rb
> +      @page_description = page_description
No bro this is for assigning page title throughout the show page tabs

2021-08-31 10:30 UTC, anondita commented on app/views/layouts/cm_admin.html.slim
> +                == render 'cm_admin/main/tabs'
It has a few extra elements bro

2021-08-31 12:50 UTC, AdityaTiwari2102 requested changes

2021-08-31 12:50 UTC, AdityaTiwari2102 commented on lib/cm_admin/models/filter.rb
> +          records = self.name.constantize.where(nil) unless records
@anondita - `self.name` will return the class here. We need the model name against which the records can be fetched from the DB.

2021-09-08 00:15 UTC, anbublacky approved these changes

2021-09-08 00:16 UTC, merged