CMAD-17 | Index page columns
commutatus/cm-admin pull request #71
Opened 2021-06-18 06:35 UTC by charith08

2021-06-21 12:50 UTC, anondita approved these changes

2021-06-21 14:14 UTC, mikevic commented on app/assets/stylesheets/cm_admin/components/_status-tag.scss
>    &.default-tag {
@charith08 - can you talk to @barath46 and figure out a way we could avoid the !important?

2021-06-21 15:24 UTC, charith08 commented on app/assets/stylesheets/cm_admin/components/_status-tag.scss
>    &.default-tag {
@mikevic - Rechecked the styling, its working without the `!important` (my bad, dom issue previously)

2021-06-21 15:25 UTC, mikevic commented on app/assets/stylesheets/cm_admin/components/_status-tag.scss
>    &.default-tag {
@charith08 - awesome!

2021-06-22 07:11 UTC, AdityaTiwari2102 requested changes

2021-06-22 07:11 UTC, AdityaTiwari2102 commented on lib/cm_admin/view_helpers/column_field_helper.rb
> +        prefix.to_s + ' ' + value.to_s + ' ' + suffix.to_s
@charith08 - Can we use interpolation here? We don't have to convert every argument to a string and it would be more readable as well.
```suggestion
        "#{prefix} #{value} #{suffix}"
```

2021-06-22 07:34 UTC, AdityaTiwari2102 approved these changes

2021-06-26 10:40 UTC, merged