newForm dsl integration
commutatus/cm-admin pull request #73
Opened 2021-06-21 07:58 UTC by anbublacky

2021-06-21 09:51 UTC, AdityaTiwari2102 commented on lib/generators/cm_admin/view_generator.rb
> +      rails g spotlight_search:filter #{name} --filters scope:datatype
@anbublacky - 
1. Do we need to add the gem dependency for spotlight?
2. Can't we have a generator for the filters in cm admin?

2021-06-21 09:51 UTC, AdityaTiwari2102 commented on lib/generators/cm_admin/view_generator.rb
> +        puts "Wrong page_type provided. It can be either index or show"
@anbublacky 
```suggestion
        puts "Wrong page_type provided. It can be either form, index, or show."
```

2021-06-21 10:46 UTC, mikevic reviewed
@anbublacky - bro, can you help me understand why we need to have view generators? Aren't most of the view files taken of by the index?

2021-06-21 12:22 UTC, anbublacky commented on lib/generators/cm_admin/view_generator.rb
> +      rails g spotlight_search:filter #{name} --filters scope:datatype
@AdityaTiwari2102 
1. We do not need to dependency on spotlight
2. No, we cannot have generator for filter alone. We can have for the entire model. But that too later we can think.

2021-06-21 12:23 UTC, anbublacky commented on lib/generators/cm_admin/view_generator.rb
> +        puts "Wrong page_type provided. It can be either index or show"
Hey bro this generator is not required. There was a merge conflict and this started showing up

2021-06-21 12:23 UTC, anbublacky commented
> @anbublacky - bro, can you help me understand why we need to have view generators? Aren't most of the view files taken of by the index?

Hey bro generator is not required. There was a merge conflict and this started showing up

2021-06-22 07:17 UTC, AdityaTiwari2102 commented on lib/generators/cm_admin/view_generator.rb
> +        puts "Wrong page_type provided. It can be either index or show"
@anbublacky - Ok. Can we remove these files? These will also get merged with the branch I suppose.

2021-06-22 12:20 UTC, AdityaTiwari2102 approved these changes

2021-06-22 12:32 UTC, mikevic requested changes

2021-06-22 12:32 UTC, mikevic commented on lib/generators/cm_admin/USAGE
> +Description:
@anbublacky - can we remove this since generators are not required?

2021-06-22 12:32 UTC, mikevic commented on lib/generators/cm_admin/templates/cm_admin_initializer.rb
>  CmAdmin.setup do |config|
@anbublacky - can we remove this since generators are not required?

2021-06-26 10:34 UTC, anbublacky commented on lib/generators/cm_admin/templates/cm_admin_initializer.rb
>  CmAdmin.setup do |config|
@mikevic Install generator is required. This initializer file will get copied

2021-06-26 10:38 UTC, anbublacky commented on lib/generators/cm_admin/USAGE
> +Description:
Removed this file. Will add it if needed.

2021-06-26 10:39 UTC, merged